### ISSUE TITLE
1.7 - blue prophecy wands dropping with currency sound and border

### ISSUE THREAD

**Issue by Hypaethral** [SayyadinaAtreides/sayya-poe-filter#4]
Haven't tested with rare wands yet.  Seems to be happening due to the "prophecy" string used for the sealed prophecy items.

https://github.com/SayyadinaAtreides/sayya-poe-filter/commit/71ff9edf0ece991f4e837dc01220cf46b24c9e1e#diff-0f1549f22e328e6f2ea38a69d2062c2cR31

**Comment by SayyadinaAtreides** [comment]
Fixing in an update now by refining those to currency classes. Thanks for the heads-up!
